import { chromium } from '@playwright/test';
const out = process.argv[2] ?? '/tmp/claude-0/shots';
const width = Number(process.argv[3] ?? 1440);
const height = Number(process.argv[4] ?? 900);
const tag = process.argv[5] ?? 'd';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width, height } });
const errors = [];
page.on('console', (m) => ['error', 'warning'].includes(m.type()) && errors.push(`${m.type()}: ${m.text()}`));
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
await page.goto('http://localhost:4173/app/?sample=1');
await page.getByTestId('results').waitFor();
await page.waitForTimeout(400);
await page.screenshot({ path: `${out}/${tag}-results.png`, fullPage: true });
await page.getByTestId('open-detail').first().click();
await page.getByTestId('detail').waitFor();
await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/${tag}-detail.png` });
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Review rules' }).count();
await page.getByRole('button', { name: /Match rules/ }).click();
await page.waitForTimeout(900);
await page.screenshot({ path: `${out}/${tag}-rules.png`, fullPage: true });
await page.getByRole('button', { name: /^Files/ }).click();
await page.waitForTimeout(300);
await page.screenshot({ path: `${out}/${tag}-files.png`, fullPage: true });
if (errors.length) console.log(errors.join('\n'));
await browser.close();
