"""
Generates independent XLSX test inputs with openpyxl (a different producer than RowSignal's own
writer) so the reader is tested on files it did not create. Output is committed to tests/fixtures.
Run: python3 scripts/make-test-fixtures.py   (requires: pip install openpyxl)
"""
import datetime as dt
import os
import openpyxl
from openpyxl.utils.datetime import CALENDAR_MAC_1904

OUT = os.path.join(os.path.dirname(__file__), "..", "tests", "fixtures")
os.makedirs(OUT, exist_ok=True)

# --- multi-sheet workbook: title rows above the header, text IDs, formulas, errors, hidden things
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Orders"
ws["A1"] = "Weekly orders report"
ws["A2"] = "generated by a script"
headers = ["Order ID", "SKU", "Qty", "Price", "Shipped", "Active", "Calc", "Notes"]
for i, h in enumerate(headers, start=1):
    ws.cell(row=3, column=i, value=h)
ws.append(["00123", "ab-1", 5, 12.5, dt.datetime(2026, 4, 3), True, "=C4*2", "line one\nline two"])   # row 4
ws.append([124, "AB-2", 0, 0.1 + 0.2, dt.datetime(2025, 12, 31), False, "=C5*2", "x & y < z"])        # row 5
ws.append([None, None, None, None, None, None, None, None])                                             # row 6 blank
ws.append(["00125", "  pad  ", 7, 1234567.891, dt.datetime(2026, 4, 3, 14, 30), True, None, None])     # row 7
c = ws.cell(row=8, column=1, value="#N/A")
c.data_type = "e"                                                                                       # row 8 error value
ws.cell(row=8, column=2, value="err")
ws.cell(row=9, column=1, value="HIDE")                                                                  # row 9 hidden row
ws.cell(row=9, column=2, value="hidden-row")
ws.row_dimensions[9].hidden = True
ws.column_dimensions["H"].hidden = True
ws.cell(row=7, column=5).number_format = "dd/mm/yyyy hh:mm"
ws.cell(row=4, column=5).number_format = "mm/dd/yyyy"

hidden = wb.create_sheet("Archive")
hidden.append(["Ref", "Value"])
hidden.append(["a1", 1])
hidden.sheet_state = "hidden"

second = wb.create_sheet("Prices")
second.append(["Code", "Price"])
second.append(["X1", 10])
second.append(["X2", 20])
wb.save(os.path.join(OUT, "openpyxl_multi.xlsx"))

# --- 1904 date system
wb = openpyxl.Workbook()
wb.epoch = CALENDAR_MAC_1904
ws = wb.active
ws.append(["Date"])
ws.append([dt.datetime(2026, 4, 3)])
ws.append([dt.datetime(1999, 12, 31)])
for r in (2, 3):
    ws.cell(row=r, column=1).number_format = "yyyy-mm-dd"
wb.save(os.path.join(OUT, "openpyxl_1904.xlsx"))

# --- 1900 date system around Excel's fake leap day
wb = openpyxl.Workbook()
ws = wb.active
ws.append(["Serial", "Date"])
for serial in (1, 59, 60, 61, 45292):
    ws.append([serial, serial])
    ws.cell(row=ws.max_row, column=2).number_format = "yyyy-mm-dd"
wb.save(os.path.join(OUT, "openpyxl_1900_serials.xlsx"))

print("fixtures written to", os.path.abspath(OUT))
